[package]
name = "wallet_service_framework"
version = "0.1.0"
authors = ["xujian <s1473561555@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
rand = { version = "0.7.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
chrono = "0.4.11"
futures = "0.1.18"
futures-util = { version = "0.3", default-features = false, features = ["async-await", "sink", "std"] }
tokio = { version = "0.2", features = ["full"] }
jsonrpc-lite = "0.5.0"
bincode = "1.3.1"
rustorm = { version = "0.17.0", features = ["with-sqlite"] }


[dev-dependencies]
env_logger = "0.7.1"


[dependencies.async-std]
version = "1.6.0"
features = ["attributes"]
