[package]
name = "wallet_service_framework"
version = "0.1.0"
authors = ["xujian <s1473561555@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.31.0"
http = "0.2.1"
log = "0.4.8"
rand = { version = "0.7.3", default-features = false }
hex = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
reqwest = { version = "0.10", features = ["json"] , default-features = false }
tokio = { version = "0.2", features = ["full"] }
chrono = "0.4.11"
tokio-tungstenite = "0.10.1"
futures-util = { version = "0.3", default-features = false, features = ["async-await", "sink", "std"] }
url = "2.0.0"
jsonrpc-lite = "0.5.0"
jsonrpc-ws = { path = "../jsonrpc-ws" }


[dev-dependencies]
env_logger = "0.7.1"


[dependencies.async-std]
version = "1.6.0"
features = ["attributes"]